console.log("==========Swap Variables assignment==========");
console.log("--------------------------------------------------");
console.log("01--> Swap Two variables");
var sweety = "Sweety";
var cutie = "Cutie";
console.log("Before swap-->", "Name One:", sweety, "Name Two:", cutie);
var temp = sweety;
sweety = cutie;
cutie = temp;
console.log("After swap-->", "Name One:", sweety, "Name Two:", cutie);
console.log("--------------------------------------------------");
console.log("02--> Swap Three variables");
var num1 = 100;
var num2 = 200;
var num3 = 300;
console.log("Before swap-->", "num1:", num1, "num2:", num2, "num3:", num3);
var temp = 100;
num1 = num2;
num2 = num3; 
num3 = temp;
console.log("After swap-->", "num1:", num1, "num2:", num2, "num3:", num3);
console.log("==================================================");
