console.log("============String Hands on Assignment============");
console.log("------------------------------------------------------------------------");
function stringHandsOn(){
    console.log("01--> Given String");
    var givenString = "  Hey you are doing good, keep it up   ";
    console.log(`Given string: ${givenString}`);
    console.log("------------------------------------------------------------------------");
    console.log("02--> Length of the string");
    var stringLength = givenString.length;
    console.log(`length of the given string: ${stringLength}`);
    console.log("------------------------------------------------------------------------");
    console.log("03--> After trim length");
    var trimGivenString = givenString.trim();
    var lengthAfterTrim = trimGivenString.length;
    console.log(`After trim length of the given string: ${lengthAfterTrim}`);
    console.log("------------------------------------------------------------------------");
    console.log("04--> Extra Spaces");
    var extraSpaces = stringLength - lengthAfterTrim;
    console.log(`Extra Spaces: ${extraSpaces}`);
    console.log("------------------------------------------------------------------------");
    console.log("05--> FIrst and Last character after trim");
    var firstCharacter = trimGivenString.charAt(0);
    var lastCharacter = trimGivenString.charAt(lengthAfterTrim-1);
    console.log(`First character after trim:${firstCharacter}, Last character after trim:${lastCharacter}`);
    console.log("------------------------------------------------------------------------");
    console.log("06--> Total Words Count");
    var wordSplit = trimGivenString.split(" ");
    var wordSplitLength = wordSplit.length;
    console.log(`Total words count in string after trim: ${wordSplitLength}`);
    console.log("------------------------------------------------------------------------");
    console.log("07--> Index of good");
    var indexOfGood = givenString.indexOf("good");
    console.log(`Index of word "good": ${indexOfGood}`);
    console.log("------------------------------------------------------------------------");
    console.log("08--> Substring and Slice");
    var subString = givenString.substring(22);
    console.log(`substring from index 22: ${subString}`);
    var slice = givenString.slice(22);
    console.log(`Slice from index 22: ${slice}`);
    console.log("------------------------------------------------------------------------");
    console.log("09-->  To check the string ends with");
    var endWordCheck = trimGivenString.endsWith("up");
    console.log(`Is the string after trim ends with "up": ${endWordCheck}`);
    console.log("------------------------------------------------------------------------");
    console.log("10-->  To check the string starts with");
    var startWordCheck = trimGivenString.startsWith("Hey");
    console.log(`Is the string after trim starts with "Hey": ${startWordCheck}`);
}
stringHandsOn()
console.log("========================================================================");